= Including Third Party Library
:toc:
:toc-placement!:

toc::[]

# Introduction

Nearly all non-trivial projects will have a requirement for including third party
libraries, headers, or programs. CMake has support for finding the path to these tools using
the `find_package()` function. This will search for CMake modules in the format
"FindXXX.cmake" from the list of folders in `CMAKE_MODULE_PATH`. On linux the
default search path will include `/usr/share/cmake/Modules`. On my system this
includes support for approximately 142 common third party libraries.

几乎所有重要项目都有包含第三方库，头文件或程序的需求。 CMake使用 `find_package()` 函数以支持寻找到这些工具的路径。这将在 `CMAKE_MODULE_PATH` 中的文件夹列表中搜索格式为 “FindXXX.cmake” 的CMake模块。在Linux上默认搜索路径将包括 `/usr/share/cmake/Modules` 。在我的系统上此路径包括了对大约142个通用第三方库的支持。


The files in this tutorial are below:

```
$ tree
.
├── CMakeLists.txt
├── main.cpp
```

  * link:CMakeLists.txt[] - Contains the CMake commands you wish to run
  * link:main.cpp[] - The source file with main

# Requirements

This example requires the boost libraries to be installed in a default system
location.

本示例要求将Boost库安装在系统中的默认位置。

# Concepts

## Finding a Package

As mentioned above the `find_package()` function will search for CMake modules in the formant
"FindXXX.cmake" from the list of folders in `CMAKE_MODULE_PATH`. The exact
format of the arguments to `find_package` will depend on the module you are looking
for. This is typically documented at the top of the `FindXXX.cmake` file.

正如刚才提到的，`find_package()` 函数会在 `CMAKE_MODULE_PATH` 中的文件夹列表中搜索格式为 "FindXXX.cmake" 的CMake模块。`find_package` 的具体参数形式取决于您要查找的模块。 这通常记录在 `FindXXX.cmake` 文件头部。

A basic example of finding boost is below:

查找 boost 的基本示例如下：

[source,cmake]
----
find_package(Boost 1.46.1 REQUIRED COMPONENTS filesystem system)
----

The arguments are:

  * Boost - Name of the library. This is part of used to find the module file FindBoost.cmake
  * 1.46.1 - The minimum version of boost to find
  * REQUIRED - Tells the module that this is required and to fail if it cannot be found
  * COMPONENTS - The list of components to find in the library.

The arguments are:

  * Boost - 库名称. 这是用于查找模块文件FindBoost.cmake的一部分
  * 1.46.1 - 查找 boost 的最低版本
  * REQUIRED - 表明这个模块是必需的，若没有找到则报错（fail）
  * COMPONENTS - 要查找的库列表。

Boost includes can take more arguments and also make use of other variables.
More complex setups are provided in later examples.

Boost的include可以使用更多参数，也可以使用其他变量。
在后面的示例中提供了更复杂的设置。


## Checking if the package is found

Most included packages will set a variable `XXX_FOUND`, which can be used to check
if the package is available on the system.

大多数包含的软件包将设置一个变量 `XXX_FOUND` ，该变量可用于检查软件包在系统上是否可用。

In this example the variable is `Boost_FOUND`:

[source,cmake]
----
if(Boost_FOUND)
    message ("boost found")
    include_directories(${Boost_INCLUDE_DIRS})
else()
    message (FATAL_ERROR "Cannot find Boost")
endif()
----

## Exported Variables

After a package is found it will often export variables which can inform the user
where to find the library, header, or executable files. Similar to the `XXX_FOUND`
variable, these are package specific and are typically documented at the top of the
`FindXXX.cmake` file.

当一个包被找到时，通常会定义一个变量以告知用户可以找到这个库、头文件或可执行文件的位置。与 `XXX_FOUND`
变量相似，这些是随软件包而定的，通常记录在 `FindXXX.cmake` 文件中。

The variables exported in this example include:

  * `Boost_INCLUDE_DIRS` - The path to the boost header files.

在此示例中导出的变量包括：
  
  * `Boost_INCLUDE_DIRS` - Boost头文件的路径。

In some cases you can also check these variables by examining the cache using
ccmake or cmake-gui.

在某些情况下，您还可以通过使用 ccmake 或 cmake-gui 命令检查缓存来检查这些变量。

## Alias / Imported targets

Most modern CMake libraries link:https://cmake.org/cmake/help/v3.6/prop_tgt/IMPORTED.html#prop_tgt:IMPORTED[export] +ALIAS+ targets in their module files. 
The benefit of imported targets are that they can also populate include directories and linked libraries.

大多数现代的CMake库会在它们的模块文件中 link:https://cmake.org/cmake/help/v3.6/prop_tgt/IMPORTED.html#prop_tgt:IMPORTED[export] +ALIAS+ 目标。导入目标的好处是它们也可以填充包含目录和链接的库。

For example, starting from v3.5+ of CMake, the
Boost module supports this. Similar to using your own ALIAS target for libraires, an +ALIAS+ in a module can make referencing found targets easier.

例如从CMake v3.5+ 开始，Boost 模块就支持（这一特性）。与使用自己的 ALIAS 用于库的情况类似，在一个模块中使用 +ALIAS+ 可以使引用找到目标更加容易。

In the case of Boost, all targets are exported using the `Boost::` identifier and then the name 
of the subsystem. For example you can use:

  * `Boost::boost` for header only libraries
  * `Boost::system` for the boost system library.
  * `Boost::filesystem` for filesystem library.

对于 Boost 的情况，所有目标都被设置为使用 `Boost::` （开头）后接子系统的名称。例如可以使用：

  * `Boost::boost` 用于只有头文件的库
  * `Boost::system` 用于 boost 系统库
  * `Boost::filesystem` 用于文件系统库

As with your own targets, these targets include their dependencies, so linking against
`Boost::filesystem` will automatically add `Boost::boost` and `Boost::system` dependencies.

如同自定义目标，这些目标也包含了它们的依赖，所以对于 `Boost::filesystem` 的连接，会自动添加 `Boost::boost` 和 `Boost::system` 的依赖。

To link against an imported target you can use the following:

要链接到导入的目标，可以使用以下命令：

[source,cmake]
----
  target_link_libraries( third_party_include
      PRIVATE
          Boost::filesystem
  )
----

## Non-alias targets

While most modern libraries use imported targets, not all modules have been updated. In the
case where a library hasn't been updated you will often find the following variables available:

  * xxx_INCLUDE_DIRS - A variable pointing to the include directory for the library.
  * xxx_LIBRARY - A variable pointing to the library path.

尽管大多数现代库都使用导入的目标，但并非所有模块都已更新。在有库未更新的情况下，您通常会发现以下可用变量：

  * xxx_INCLUDE_DIRS - 指向库的包含目录的变量。
  * xxx_LIBRARY - 指向库路径的变量。

These can then be added to your +target_include_directories+ and +target_link_libraries+ as:

它们被添加到 +target_include_directories+ 和 +target_link_libraries+ 如下所示:

[source,cmake]
----
# Include the boost headers
target_include_directories( third_party_include
    PRIVATE ${Boost_INCLUDE_DIRS}
)

# link against the boost libraries
target_link_libraries( third_party_include
    PRIVATE
    ${Boost_SYSTEM_LIBRARY}
    ${Boost_FILESYSTEM_LIBRARY}
)
----

# Building the Example

[source,bash]
----
$ mkdir build

$ cd build/

$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
boost found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/H-third-party-library/build

$ make
Scanning dependencies of target third_party_include
[100%] Building CXX object CMakeFiles/third_party_include.dir/main.cpp.o
Linking CXX executable third_party_include
[100%] Built target third_party_include
matrim@freyr:~/workspace/cmake-examples/01-basic/H-third-party-library/build$ ./
CMakeFiles/          third_party_include
matrim@freyr:~/workspace/cmake-examples/01-basic/H-third-party-library/build$ ./third_party_include
Hello Third Party Include!
Path is not relative
$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   filesystem
--   system
boost found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/matrim/workspace/cmake-examples/01-basic/H-third-party-library/build

$ make
Scanning dependencies of target third_party_include
[100%] Building CXX object CMakeFiles/third_party_include.dir/main.cpp.o
Linking CXX executable third_party_include
[100%] Built target third_party_include

$ ./third_party_include
Hello Third Party Include!
Path is not relative

----
